name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['21']
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check
        run: ./gradlew check
